services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tafakkur-web
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      es:
        condition: service_healthy
    volumes:
      - .:/app:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: tafakkur-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.name=tafakkur-es
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  es_data: